### ISSUE TITLE
Leaking system info in citations.bib

### ISSUE THREAD

**Issue by thermokarst** [lozuponelab/q2-SCNIC#2]
Specifically the `file` attr:

- [here](https://github.com/shafferm/q2-SCNIC/blob/83fa2a9889e154355f2f93f6b03df8e1a125f1f8/q2_SCNIC/citations.bib#L15)
- and [here](https://github.com/shafferm/q2-SCNIC/blob/83fa2a9889e154355f2f93f6b03df8e1a125f1f8/q2_SCNIC/citations.bib#L31)

**Comment by shafferm** [comment]
Oops. Didn't check after my mendely export. Thanks @thermokarst.
